### ISSUE TITLE
Game crashes ("invalid java runtime configuration")

### ISSUE THREAD

**Issue by Gremzon** [paulevsGitch/BCLib#101]
when i try to lauch minecraft with bclib (1.3.0 and 1.3.1), the game shows me this error window. 1.2.5 works just fine but makes my server crashes when i try to start it.  
![image](https://user-images.githubusercontent.com/99607986/153764587-2af3fe2f-c342-49c9-98f4-efcf933f4446.png)

**Comment by paulevsGitch** [comment]
Please provide your logs
