### ISSUE TITLE
My game crashes when opening my Better Minecraft world, and it says this mod might be the issue. 

### ISSUE THREAD

**Issue by Mister-Narwhal** [paulevsGitch/BCLib#103]
Error code is here: https://crashy.net/71JIWGd36PuwAnYYdtbE

Any help would be appreciated!

**Comment by paulevsGitch** [comment]
Looks like your world is corrupted, is this fresh world?

**Comment by Mister-Narwhal** [comment]
Here you go. This is after i played for a bit more after removing the bclib and associated betterx mods
[New Compressed (zipped) Folder.zip](https://github.com/paulevsGitch/BCLib/files/8105029/New.Compressed.zipped.Folder.zip)
.

**Comment by Mister-Narwhal** [comment]
actually never mind i tried again and its working now.

**Comment by Mister-Narwhal** [comment]
i appreciate you helping me out, though. thanks very much!
