### ISSUE TITLE
Game crashes ("invalid java runtime configuration")

### ISSUE THREAD

**Issue by entwinedent** [paulevsGitch/BCLib#106]
[2022-02-21-7.log](https://github.com/paulevsGitch/BCLib/files/8109291/2022-02-21-7.log)
looks like the mods extraalchemy , and nether chest are conflicting with your mod or maybe not pulling the right dependency's , as well as libcd which is not a mod that i know of ,

Describe the bug
add BClib 1.3.4 from 1.2.4 and crashes with your mod as well as extra alchemy and libcd(don't know which mod is using this resource)

To Reproduce

    Go to 'add BClib 1.3.4'
    Click on 'play game'
    Scroll down to 'logs'
    See bug

Expected behavior
start with no errors

Screenshots

Pastebin links

[2022-02-21-7.log](https://github.com/Kir-Antipov/nether-chest/files/8109436/2022-02-21-7.log)

Environment (please complete the following information):

    Mod Version: [BClib 1.3.4] anything 1.3.0+
    MC Version: [1.18.1]
    Fabric Version: [0.13.2]
    Fabric API version: [fabric-api-0.46.4+1.18]
    System: [e.g. Windows 7]
    Installation type: [SinglePlayer]

Additional context
Add any other context about the problem here, like other mods that you think might be involved in the problem.

**Comment by entwinedent** [comment]
From the ExtraAlchemy ticket, Judging by the last error, it seems like some mod is trying to load an old version of bclib api.

EA does not use it. If you remove Extra Alchemy the bug should still happen , and it does still happen after removing ExtraAlchemy.

**Comment by entwinedent** [comment]
thats weird because i updated and its still calling on old mod data ?,
[latest.log](https://github.com/paulevsGitch/BCLib/files/8109862/latest.log)

**Comment by entwinedent** [comment]
Loading 424 mods:
	- additionaladditions 3.0.1
	- additionalbars 2.2.1
	- adorn 3.3.1+1.18.1
	- advanced_runtime_resource_pack 0.5.4 via secretrooms
	- advancements-enlarger 0.2.4
	- adventurez 1.4.7
	- ae2 10.1.0-beta.2
	- alloy_forgery 2.0.9+1.18
	- ambientenvironment 7.0+17
	- amecsapi 1.3.3+mc1.18-pre1 via backslot
	- amplified_nether 1.0.1
	- animal_feeding_trough 1.0.3+1.18.1
	- animatica 0.3+1.18
	- aqupdcaracal 1.18-1.3.5.1
	- aqupdgrizzly 1.18-1.2.2
	- architects_palette 1.6
	- architectury 3.7.22
	- artifality 0.5.5
	- attributefix 1.0.3
	- autoconfig1u 3.3.1
	- axolotlitemfix 1.1.3
	- backslot 1.2.5
	- backslotaddon 1.0.8
	- balm-fabric 2.4.1+0
	- basicaiots 1.3.3+1.18.1
	- basicshields 1.2.1-1.18.1
	- bcc fabric-1.0.4
	- bclib 1.3.4
it is using your new version in the log file

**Comment by paulevsGitch** [comment]
> thats weird because i updated and its still calling on old mod data ?, it is using your new version in the log file, i also removed Extra Alchemy and nether chest to see if that made a difference

You are using outdated mod versions with library, both mod and library versions should be up to date

**Comment by entwinedent** [comment]
so since there is no updated versions of the mods that match your new version of BC lib then the mods crash the game k, so the mod authors need to update to your new version of BClib

**Comment by entwinedent** [comment]
So ive done some testing and there is a mod thats generating this mod , libcd-3.0.3+1.16.3-72e9d990eea2f316 ,which is a processor mod, which is giving cascading failures with nether chest , BClib, and Extra Alchemy.

**Comment by entwinedent** [comment]
So this was annoying I was adding BClib 1.3.4 and a sub-process mod called libcd-3.0.3+1.16.3 crashed my modpack , it was hard to find since the only error was the libcd. but the mod thats crashing everything is better-end-1.0.0 , but everything works now but that one mod of like 300 :P
