### ISSUE TITLE
Corrupted world from bclib 1.2.5 to 1.3.4 update

### ISSUE THREAD

**Issue by itsdinkd** [paulevsGitch/BCLib#107]
Hello, creator of Another Quality Modpack 2 here. 

Recently, we updated the modpack to v2.0.5, including in this update was Better End (1.0.2 from 1.0.1), Better Nether (6.0.10 from 6.0.9), and BCLib (1.3.4 from 1.2.5).

When I released this, every player was crashing as soon as they explored Nether for more than 2 seconds. players from single player, on their own servers, our dedicated servers, and even locally when I tried to reproduce. We ran binary searches, removing mod by mod by mod, and nothing did it. The crash log said it was xaero minimap (was not updated), and then removing that, it was reporting classes when crashing. Xaero's Minimap wasn't touched in weeks, so I know its not this mod. 

Long story short, I tried to figure out which mods and ultimately discovered it. I went on my world locally from the last AQM2 version, where it used 6.0.9 BN, 1.0.1 BE, 1.2.5 BCLib, and went into the nether to make sure there  wasn't a crash with these versions, and there wasn't. I then updated all three of those mods to their latest, and then I opened up the game, joined the world, and BCLib told me it needed to run patch fixes, so I let it do its thing. 

When it finished, I joined the Nether, and I crashed. The same crash other people experienced from my 2.0.5 modpack update, but I wasn't on 2.0.5, I was on 2.0.4.1, with just the three mods updated. 

As requested, here is my world folder, and logs. 

Note: please ignore the stoneholm message, I had removed stoneholm in my local instance, it works just fine without the structure mod, as I tested before I updated BN,BCLib,BE and had no issues with stoneholm being removed. 

Latest Log **(prior to updating the three mods, and playing just fine. Teleported to Nether, flew around for a minute or two and exited)**: https://gist.github.com/itsdinkd/82e987c1bac83f6f5a5dac732343f458

Latest Log **(when updating the three mods to latest and being forced to apply fixes and crashing in nether)**: https://gist.github.com/itsdinkd/e40c9d06f38d32bac608697cb9560332

Latest Log **(From downgrading the three mods back to what they were at before, **after** letting BCLib apply patches, and crashing in nether)**: https://gist.github.com/itsdinkd/802be0ccea03c36bfb7e018c17ae9fc3

World save: https://www118.zippyshare.com/v/0smZbiaT/file.html

**Comment by itsdinkd** [comment]
**Steps to reproduce**
1. Download AQM2 2.0.4.1 on Curseforge
2. Create world, join nether
3. Exit, Update BN + BE + BCLib to latest
4. Join Nether
5. fly around for 5 seconds
6. Crash

**Comment by itsdinkd** [comment]
Cause of this issue was disabling ore in 1 file, blocks.json, and not the generator.json file. Wasn't aware that you needed to disable ore in both files. Also, having duplicate entries b being added to configs over time by updating, where the only difference is comments. I disabled ore on duplicated lines, and once cleared, and enabled ore, crash stopped.

**Comment by paulevsGitch** [comment]
As this is a BN issue and is not related to BClib I'm closing it
