### ISSUE TITLE
invalid java runtime configuration

### ISSUE THREAD

**Issue by SkeleborgM** [paulevsGitch/BCLib#110]
youve definitly gotten questions about this before but im having trouble finding actual answers just through watching other peoples question about it or googling it so i thought i might send my own version of the question. i try to run the game with the mods required for better nether and better end: fabric and BCLib (sometimes plus mod menu) but without BCLib it says i require it and with it the game crashes and gives me the whole "invalid java runtime configuration" message and i dont know what to do to fix it.
[2022-03-03-7.log.gz](https://github.com/paulevsGitch/BCLib/files/8181141/2022-03-03-7.log.gz)

**Comment by paulevsGitch** [comment]
You are loading Minecraft 1.18.2, with mods for 1.17, with java 16. As a result it doesn't work. Use mods versions only with correct MC version and correct Java version (for 1.18 it will be java 17)

**Comment by SkeleborgM** [comment]
thanks :)
