### ISSUE TITLE
invalid java runtime configuration (second time today (as in second time asking, not second time trying))

### ISSUE THREAD

**Issue by SkeleborgM** [paulevsGitch/BCLib#111]
sorry im back again so soon. but i made sure to update everything, redownload some things etc. and it should've worked at this point but it refuses to.

[latest.log](https://github.com/paulevsGitch/BCLib/files/8181628/latest.log)

**Comment by SkeleborgM** [comment]
I also made sure to get jarfix alongside the latest version of java but still

**Comment by paulevsGitch** [comment]
Mods are for 1.18.1, not for 1.18.2
