### ISSUE TITLE
BCLib Crash on startup

### ISSUE THREAD

**Issue by JovierCujoh** [paulevsGitch/BCLib#113]
Hello, I'm using Pop! OS 21.10 and I'm trying to use Fabric 1.18.2 with BCLib (and Fabric API), but it just keeps crashing. I am using the latest version of bclib (1.3.4) and fabric api (0.47.8 1.18.2).

Here's the log: https://hastebin.skyra.pw/ixowadinur.bash

**Comment by paulevsGitch** [comment]
BCLib is for MC 1.18.1, not 1.18.2

**Comment by Niketats** [comment]
is 1.18.2 planned?

**Comment by paulevsGitch** [comment]
Yes
