### ISSUE TITLE
BCLib is generating massive lag with Betterend spawn condition check in certain biomes

### ISSUE THREAD

**Issue by aria1th** [paulevsGitch/BCLib#115]
https://spark.lucko.me/rNywA1oZTb
related line of code :
https://github.com/paulevsGitch/BCLib/blob/main/src/main/java/ru/bclib/api/spawning/SpawnRuleBuilder.java#L227

seems like its occuring at shadow forest biome?

**Comment by paulevsGitch** [comment]
Looks like something redirects MC search algorithm which is the source.

![image](https://user-images.githubusercontent.com/17707380/159162518-2285e644-7935-42fe-abea-fd7118101f91.png)

Function that you pointed is applied to almost all BE entities and it is a check that there are not too much entities of same type in surrounding area. Its performance is directly related to world functions, and due to screen above vanilla functions were changed, so probably the issue is with another mod

**Comment by aria1th** [comment]
Most suspicious mod is Lithium, hmm...

**Comment by paulevsGitch** [comment]
If you are interested why this check exists - it prevents mobs from spawning up to large numbers (with huge memory leak after that). Minecraft mob spawn system is not balanced (especially for modded entities), so the game can try spawn really huge amount of them

![image](https://user-images.githubusercontent.com/17707380/159163443-47d44294-047a-41b2-94a5-b2b88aedb50b.png)

Another reason - it will balance entity count for each area, for example there will be no areas filled with 200+ mobs while others stay empty. This is important for ambient and hostile mobs

**Comment by aria1th** [comment]
I guess mobcaps exist for that reason but balancing might be a thing, I'm trying to reproduce it without other mods.
Wouldn't it better to use spawn potential in 1.16+?

**Comment by aria1th** [comment]
yes seems its lithium issue

**Comment by paulevsGitch** [comment]
> Wouldn't it better to use spawn potential in 1.16+?

This function was added as a spawn rule. Spawn rules are vanilla features to control mob spawning. There are other rules that are used in BN and BE, for example distance from the ground for flying mobs, current game rules (that affects hostile mobs), light level and so on. I’m not sure on what version they appeared, but they exists in 1.17 and 1.18. BCLib has a builder for them

> I guess mobcaps exist for that reason

Vanilla mob caps have some weird behavior, for some reasons they may not affect some mobs, especially ambient creatures. I think that some mobs may be even hardcoded in caps. So, adding one more spawn conditions fixes all issues with caps, mobs overspawning and memory leaking
