### ISSUE TITLE
Eden Ring GuideBook displays garbled

### ISSUE THREAD

**Issue by Slarper** [paulevsGitch/BCLib#117]
![unfixed 1](https://user-images.githubusercontent.com/98243861/160162709-568d3fcf-0954-488c-8f28-13c71303c02b.png)
![unfixed 2](https://user-images.githubusercontent.com/98243861/160162720-dfdae723-9d99-4ab0-9820-8309267464a9.png)

This bug occurs in Eden Ring but should be fixed in BCLib ( their author are the same. )

I will create a pull request to fix it later and explain about it.

**Comment by Slarper** [comment]
The Bug Explanation :

The Class `BCLib/src/main/java/ru/bclib/util/JsonFactory`'s method

```java
public static JsonObject getJsonObject(ResourceLocation location)
```

calls

```java
public InputStreamReader(InputStream in)
```

which decodes `InputStream in` by computer system's default charset.

It means potential decoding bugs in some systems, like Chinese-environment Windows( which default charset is cp936 )

Besides, in Eden Ring mod, GuideBook' content depends on `resources/assets/edenring/lang/book/en_us.json` which includes lines like

```
            "§8● §lWorld of Eden",
```

and both `§` and `●` will become garbled.

So the solution is use 
```java
public InputStreamReader(InputStream in, Charset cs)
```

instead of the original.

**Comment by Slarper** [comment]
I have created a pull request. I will be glad to see it merged.

**Comment by paulevsGitch** [comment]
Thank you for your PR

**Comment by paulevsGitch** [comment]
Should work fine since 1.4
