### ISSUE TITLE
BCLib crashes when trying create a new singleplayer world.

### ISSUE THREAD

**Issue by thatone-overthere** [paulevsGitch/BCLib#120]
BCLip crashes my game whenever I try to create a new singleplayer world with the crash phase "starting integrated server". Only after taking betterend, betternether and BCLip out did it allow me to load a new world.

I'm using 1.18.1 fabric, BCLip 1.2.4, Betternether 6.0.8 and Betterend 1.0.0.

I've found any other version of BCLip crashes even more then usual. I'm still able to connect to servers and load past worlds, just not create new worlds.

Here's the crash log:
[crash-2022-03-27_18.48.20-client.txt](https://github.com/paulevsGitch/BCLib/files/8357168/crash-2022-03-27_18.48.20-client.txt)

**Comment by paulevsGitch** [comment]
All mod versions that you have are outdated, please use the latest that are available for this MC version.
In you logs I also don't see anything that indicates that reason is BCLib or one of these mods

**Comment by thatone-overthere** [comment]
I upgraded the mods and it's worked, although last time I tried it broke, perhaps you fixed the issue already and I was being stupid. Thank you anyways.
