### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by HacoKavanah** [paulevsGitch/BCLib#123]
[latest (2).log](https://github.com/paulevsGitch/BCLib/files/8404008/latest.2.log)

**Comment by paulevsGitch** [comment]
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector onUse$ItemStack$isOf(Lnet/minecraft/class_1799;Lnet/minecraft/class_1792;)Z in moretags.mixins.json:item.shears.PumpkinBlockMixin from mod moretags failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap MoreTags-refmap.json

This is MoreTags issue, not BCLib issue
