### ISSUE TITLE
Incompatible with Cull Leaves and probably other mods from the same devs

### ISSUE THREAD

**Issue by Sunconure11** [paulevsGitch/BCLib#127]
https://pastebin.com/vZJU6dxu

**Comment by paulevsGitch** [comment]
> Critical injection failure: Redirector onUse$ItemStack$isOf(Lnet/minecraft/class_1799;Lnet/minecraft/class_1792;)Z in moretags.mixins.json:item.shears.PumpkinBlockMixin from mod moretags failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap MoreTags-refmap.json

Issue is in MoreTags and I s not related to BCLib
