### ISSUE TITLE
bclib won't let me open java without crashing

### ISSUE THREAD

**Issue by archelaios** [paulevsGitch/BCLib#129]
I'm trying to use Better Nether and Better End for Minecraft 1.18.2, and I downloaded everything that they said I needed. I've tried with just fabric and it opens Minecraft just fine. I've tried with the bclib and fabric, but it crashes. I've tried with just the better end and the better nether both with the fabric and bclib, but it always crashes. I've tried multiple versions of bclib, different versions of fabric, and the two better mods, but nothing is working. Everything is up to date, and I've restarted my computer like 5 times. Does anyone know about this and can help me figure out what is happening? It won't even give me a crash report, just that the game crashed and something about java runtime.

**Comment by paulevsGitch** [comment]
Better End is not available for 1.18.2.
Crash report without logs is incorrect, please provide your logs
