### ISSUE TITLE
BCLIB incompatible with paradise reborn

### ISSUE THREAD

**Issue by Deceiverr13** [paulevsGitch/BCLib#130]
I just discovered that bclib 1.4.3 is incompatible with paradise lost - the aether reborn 1.6.8 on 1.18.2. Would greatly appreciate if this could be fixed!!

**Comment by paulevsGitch** [comment]
Technically this is a duplicate of #128

**Comment by Deceiverr13** [comment]
How is this a duplicate? It's a different mod.

**Comment by paulevsGitch** [comment]
Paradise Reborn use embedded MoreTags inside, issue with MoreTags is already opened, so it is duplicate

**Comment by Deceiverr13** [comment]
Ah, I see. Makes sense then. Thanks for clarifying!
