### ISSUE TITLE
Incompatible with Paradise Lost

### ISSUE THREAD

**Issue by ErinPhoenix** [paulevsGitch/BCLib#133]
https://pastebin.com/WYhTxw2y

Game crashes with both BCLib and Paradise Lost. It starts with one or the other removed.

**Comment by paulevsGitch** [comment]
Duplicate of #128 and #130

**Comment by Laifsyn** [comment]
![image](https://user-images.githubusercontent.com/99366187/163864017-d235e061-c8fd-45e3-9aed-fcced5d0b52b.png)
