### ISSUE TITLE
[1.18.2] Can't synch mods

### ISSUE THREAD

**Issue by pewblaze** [paulevsGitch/BCLib#135]
Hi, i can't synch the mods on the server. The option is grey & uncheckable. Config files work fine.
1.18.2 (Fabric Loader 0.13.3)
bclib-1.4.3

![2022-04-21_21 03 42](https://user-images.githubusercontent.com/96242065/164618253-f31e6310-d42e-40ef-9c36-6f08a1805d63.png)

my client & server.json
https://gist.github.com/pewblaze/2c18942ca8ee2a96c27a5226b78ec78b

**Comment by paulevsGitch** [comment]
Probably this is same/similar to #109, but I'm not sure

**Comment by pewblaze** [comment]
Sorry for the late response. It works now i think :) !
