### ISSUE TITLE
Guardian detected an incompatible world 

### ISSUE THREAD

**Issue by KawaiiUzi** [paulevsGitch/BCLib#138]
Every time i start up one of my worlds i keep getting *Guardian detected an incompatible world* and when i try to play on my own world server to play with friends that keeps ending up crashing the server for us. Not sure why it keeps saying this? is there a mod messing this up everytime? i can play alone just annoying seeing it everytime to *patch my world* and annoying when i am trying to play with a friend it just won't work.

**Comment by paulevsGitch** [comment]
Please post your server logs

**Comment by KawaiiUzi** [comment]
Server Logs? if you mean when my friend joins we use some off brand softwere to connect to each other but it is always bclib causing this issue for my friend to crash cause of *Guardian detected an incompatible world* so he can't join me which means we can't use betterend or any of that stuff.

**Comment by paulevsGitch** [comment]
Please provide any logs. BCLib fixers GUI is single player, while you are talking about multiplayer

**Comment by KawaiiUzi** [comment]
[2022-05-03-4.log](https://github.com/paulevsGitch/BCLib/files/8619151/2022-05-03-4.log)
![Screenshot (889)](https://user-images.githubusercontent.com/89453508/166656260-9f26f5d1-f6a8-406b-8c8b-843363e546e5.png)

**Comment by KawaiiUzi** [comment]
As it says, Some installed mods did change, but the thing is i have not installed mods inawhile. This issue makes so my friends can't play with me on a LAN server!

**Comment by paulevsGitch** [comment]
> ava.lang.UnsupportedOperationException: null
	at com.google.common.collect.ImmutableMap.remove(ImmutableMap.java:851) ~[guava-31.0.1-jre.jar:?]
	at svenhjol.charm.helper.AdvancementHelper.lambda$filterAdvancements$4(AdvancementHelper.java:45) ~[charm-fabric-1.18-4.0.0.jar:?]

Error in logs before crash are related to charm, not to BCLib

**Comment by KawaiiUzi** [comment]
Ok so the issue causing this is charm not bclip

**Comment by KawaiiUzi** [comment]
i'll try it out and see what happens

**Comment by KawaiiUzi** [comment]
I am still getting the issue, *Guardian detected an incompatible world*

**Comment by paulevsGitch** [comment]
This means that your level.dat has incorrect biome sources, try to fix it manually

**Comment by KawaiiUzi** [comment]
What is that? and how do i fix that.

**Comment by paulevsGitch** [comment]
You can look into tutorial in Discord server or in BE wiki
