### ISSUE TITLE
BCLib keeps crashing my client, but only one versions 1.3.0 and above.

### ISSUE THREAD

**Issue by yonshee** [paulevsGitch/BCLib#141]
I'm trying to use BCLib for both betternether and betterend on 1.18.1.
When I try to load the game with version 1.3.0 and above (required for betternether), my game crashes with exit code 1. 
When I try to load with with 1.2.1, it works just fine. 

Let me know if I need to send in log files and if so, how I can do that. I am very stressed over this.

**Comment by paulevsGitch** [comment]
You need to use same version of library as mod require. Looks like your mods are outdated comparing to BCLib itself

**Comment by paulevsGitch** [comment]
1.18.1 is also not supported anymore. If it is possible please upgrade to 1.18.2
