### ISSUE TITLE
BCLib's recipe manager mixin actually does not return consistent ordered recipes

### ISSUE THREAD

**Issue by aria1th** [paulevsGitch/BCLib#144]
Case : if there is 3 recipes with one material, its result will be different with every reboot.
tin dust -> tin ingot ( indrev / modern industrialization / tech reborn) -> returns inconsistent result

Instead of returning 0, it should use something like this (at least this works, without resoureLocation access)

```				return b1 ^ b2 ? (b1 ? 1 : -1) : (v1.getResultItem().getDescriptionId().compareTo(v2.getResultItem().getDescriptionId()));```

**Comment by paulevsGitch** [comment]
Original MC code provided an unsorted recipes, so that's why sorting below "minecraft/modded" level was not implemented. Now the order should be always fixed

**Comment by quiqueck** [comment]
Fix Should be in BCLib 1.4.7.
