### ISSUE TITLE
Crash on startup with Promenade 2.6.2

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [paulevsGitch/BCLib#145]
**MC** 1.18.2
**BCLib** 1.4.6
**Promenade** 2.6.2

When BCLib is installed together with Promenade 2.6.2 (specifically that version), the game crashes on startup. Initially reported to Promenade, but was suggested to report here instead - https://github.com/DawnTeamMC/Promenade/issues/83#issuecomment-1138523591.

Logs: https://gist.github.com/Footage2-Amply-Pounce/e9120c27dfe1f30304f7c92ab23b4751

**Comment by Hugman76** [comment]
After another report on my mod, it seems like it is a mistake of mine. I will not be able to investigate the issue further for the next 5 hours. I will contact you when I will find the exact source of the issue.

**Comment by paulevsGitch** [comment]
Hm, I looked into BCLib code at this position and seems like there is no check that key-value is complete or not (as by default they are always complete), so some small changes in Biome API should fix this (and other similar potential errors from other mods)

**Comment by paulevsGitch** [comment]
It fixes crash on startup, but world will crash on creation due to missing registry entries. Looks like all biomes have keys, but don't have values in registry

**Comment by Hugman76** [comment]
The biome that was causing the crash actually gets its value from Promenade's datapack, hence why it has no value before creating a world. Does your code fire before or after the Fabric API loads mod datapacks on the "Create World" screen?

**Comment by paulevsGitch** [comment]
> Does your code fire before or after the Fabric API loads mod datapacks

Loader that works with Fabric Biomes API applies on post-init, and datapacks biome loader applies on server/level startup. Originally it was created when Fabric Biome API applied only to hardcoded biomes, was this changed?

**Comment by Hugman76** [comment]
It seems like they need to be hardcoded, but their API only requires registry keys as input, so it would make sense that it would support json biomes

**Comment by paulevsGitch** [comment]
This should work fine in 1.4.7 and in future versions too, so I'm closing this
