### ISSUE TITLE
Breaks texture rendering 1.18.2 questcraft 1.3.0

### ISSUE THREAD

**Issue by DrEMartstud** [paulevsGitch/BCLib#147]
BC Lib breaks texture renderer 
Attaching logs

[2022-06-01-5.log](https://github.com/paulevsGitch/BCLib/files/8822732/2022-06-01-5.log)

**Comment by DrEMartstud** [comment]
Here is another shorter log

[latest.log](https://github.com/paulevsGitch/BCLib/files/8822766/latest.log)

**Comment by paulevsGitch** [comment]
If you use mods that conflicts with Fabric rendering API - use Indium to fix missing textures and models
