### ISSUE TITLE
Incendium 'Overwriting' BClib generation 

### ISSUE THREAD

**Issue by KindofKay** [paulevsGitch/BCLib#151]
I'm attempting to run **BetterNether alongside Incendium**; as I understand that should be possible? 
I'm running a 1.18.2 fabric server.

In the level.dat file, every time Incendium is present, the 'biome_source' entries are completely different and don't incorporate BClib generation at all. I end up with incendium biomes only, while the rest of BetterNether is preserved.

How can I avhieve the generation of both biome groups?

![w](https://user-images.githubusercontent.com/113100247/201107429-3d457502-aa16-4ef1-92ef-599585385d35.png)
![wo](https://user-images.githubusercontent.com/113100247/201107433-7e4153d6-c955-4b26-87f4-c16e6f5e1d7a.png)

**Comment by paulevsGitch** [comment]
In 1.18.2 it is possible only with datapack modification (you need to remove the_nether.json from it). In 1.18.0 and 1.19+ it is possible by default without any modifications.

Please use [new issue tracker](https://github.com/quiqueck/BCLib/) for all BCLib-related issues, this is an old Git
