### ISSUE TITLE
BetterX & Large Biomes preset on server

### ISSUE THREAD

**Issue by PlazmaKG** [paulevsGitch/BCLib#152]
I can't figure out what the preset for BetterX & Large Biomes when using a server. I can't find that information in documentation, or really anywhere. If I want BetterX & Large Biomes, what do I put into level type in server.properties? Thanks :P

Using Minecraft 1.19.2

**Comment by paulevsGitch** [comment]
Don't use old issue tracker for issues, use [new one](https://github.com/quiqueck/BCLib/) instead
This question was also answered in Discord server, it is bclib:large
