### ISSUE TITLE
Minecraft Crash

### ISSUE THREAD

**Issue by FireFall-YT** [paulevsGitch/BCLib#17]
When i try to launch minecraft 1.17, fabric says: "Could not find required mod: bclib requires {fabricloader @ [>=0.11.6]}" Can anybody help?

**Comment by FireFall-YT** [comment]
I'm using Fabric Loader 0.11.6.

**Comment by paulevsGitch** [comment]
Its better to migrate to 1.17.1, 1.17 support will be dropped soon as there are many bugs. Probably this is just one of them (and this one probably happened in Fabric API itself)
