### ISSUE TITLE
Several instances of client code that shouldn't be running on server

### ISSUE THREAD

**Issue by hugeblank** [paulevsGitch/BCLib#2]
Was unsure whether to report this on BetterEnd or here, but I've got build paulevsGitch/BetterEnd@c8cef8e055784800e8d66196af872335d0066dab of BetterEnd running on my server reporting that `ColorUtil` from BCLib cannot be run on server, and [sure enough](https://github.com/paulevsGitch/BCLib/blob/2a079b407d7c79c6895fd48fb4dc7913bf0196f8/src/main/java/ru/bclib/util/ColorUtil.java#L24). I pulled up both in an IDE to see what was going on and if I could fix it and the more I looked the more I find instances where client code is being run where the server has access to. So far I've found `ColorUtil`, and `BaseTerrainBlock` to have offending code, but given time I'm sure I could find more.

**Comment by paulevsGitch** [comment]
Hi, as this Lib and BE are unstable you can use [the latest commit](https://github.com/paulevsGitch/BetterEnd/commit/df71f23d353ec682fc6374fada05d08258c432ed) before BCLib dependency was added. This issue is already know, but thank you for report

**Comment by hugeblank** [comment]
Actually that was something I tried and it didn't seem to work. I think something in the experimental branch made its way into BCLib, and was the cause of the second `BaseTerrainBlock` related crash I was experiencing. I reverted back one step further to paulevsGitch/BetterEnd@df71f23d353ec682fc6374fada05d08258c432ed and things worked well.

**Comment by paulevsGitch** [comment]
Looks like this issue is now fixed, so I'm closing this
