### ISSUE TITLE
Tags applied to air

### ISSUE THREAD

**Issue by Mincraftr** [paulevsGitch/BCLib#25]
Bit of an odd case, and should probably just be handled better by the mods using BCLib, but if a block/item is disabled and addTag in TagAPI still gets called it'll end up just adding the tag to minecraft:air. Adding a check that block/item.asItem() isn't Blocks.AIR/Items.AIR resolves this on the BCLib side.

**Comment by paulevsGitch** [comment]
Fixed in 0.3.0
