### ISSUE TITLE
Loading Loop v0.4.0

### ISSUE THREAD

**Issue by Toilet-Man** [paulevsGitch/BCLib#33]
Here is the launcher log: [launcher_log.txt](https://github.com/paulevsGitch/BCLib/files/7220373/launcher_log.txt)

Step to reproduce:
1. Start Minecraft
2. Red load page loads up
3. There you go!

**Comment by paulevsGitch** [comment]
You are using BetterEnd with incorrect BCLib version. BE 0.11 should be used only with BCLib 0.3, BCLib 0.4 was not released yet, GitHub version it is a preview version for modders
