### ISSUE TITLE
BCLib 0.4.2 crash on startup

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [paulevsGitch/BCLib#34]
**MC** 1.17.1
**Fabric** loader 0.12.4; API 0.41.3
**BCLib** 0.4.2

Latest.log: https://gist.github.com/Footage2-Amply-Pounce/04d7be1f83b59d379e135c1f1ec6f69c

Crash report: https://gist.github.com/Footage2-Amply-Pounce/f862d96140fcce653406344e8eb22148

**Comment by quiqueck** [comment]
Thanks for the report. We'll investigate...

**Comment by quiqueck** [comment]
Possible fix implemented in b7c83923ea70de3e59fdd8364df4bfb03a32cbdc

**Comment by paulevsGitch** [comment]
Fixed in 0.4.3

**Comment by red2blue** [comment]
You should really really put that in the change log that 0.4.3 requires modloader 0.12 and 0.4.2 requires modloader 0.11 

Or at least add a required dependacy

**Comment by quiqueck** [comment]
It is not supposed to be like this, and we will release an update shortly. I'll update the change-logs in the meantime.

**Comment by Miskler** [comment]
```
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'bclib'!
```
14.06.2023

**Comment by itsdinkd** [comment]
that error log tells them nothing. you need to post the entire stack trace @Miskler

**Comment by paulevsGitch** [comment]
This is also an old issue tracker, please use [the new one](https://github.com/quiqueck/BCLib/issues)

**Comment by Miskler** [comment]
> that error log tells them nothing. you need to post the entire stack trace @Miskler

I'm too lazy to look for a log. excuse me)

**Comment by itsdinkd** [comment]
> > that error log tells them nothing. you need to post the entire stack trace @Miskler
> 
> I'm too lazy to look for a log. excuse me)

Good luck getting any help with that attitude

**Comment by Miskler** [comment]
I'm not interested in your mod
