### ISSUE TITLE
Make mod list sync/checks opt in

### ISSUE THREAD

**Issue by Patbox** [paulevsGitch/BCLib#38]
Currently, this mod will warn players joining servers if any of the mods are mismatched. This should be opt in instead of checking all by default, as it causes lots of false positives with mods that are optional on either client or server.

Example mods effected by this: [Lithium](https://www.curseforge.com/minecraft/mc-mods/lithium), [Universal Graves](https://www.curseforge.com/minecraft/mc-mods/universal-graves) (required only on server, but works on singleplayer), [Entity View Distance](https://www.curseforge.com/minecraft/mc-mods/entity-view-distance) and many, many more

**Comment by quiqueck** [comment]
We'll make it opt-in on the server in the next version. For now, you can disable that behavior for all clients when you replace
`"sendAllModInfo [default: true]": true`
with
`"sendAllModInfo [default: true]": false`

in *config/bclib/server.json* on the server.

**Comment by Patbox** [comment]
I hope as opt in you mean that mods need to declare being required instead guessing it as there is lots of way automatic detection can break (see projects like polymer, which allows you to add registry entries without requiring mods on client)

**Comment by quiqueck** [comment]
When the option above is deactivated, only Mods that actively opted in through the API are sent for comparison.

The above option will be off by default in the next version, and we will add an exlude list, where (when you choose to reactive the feature on the server) you can specify which mods to ignore for the comparison.

**Comment by quiqueck** [comment]
Oh, and server-only mods should already be excluded from the comaprison.

**Comment by Patbox** [comment]
Thats good. Also keep in mind that most mods designed for servers will work on singleplayer (including polymer)

**Comment by paulevsGitch** [comment]
Fixed & added in 0.5.0
