### ISSUE TITLE
0.5.0 crash on startup

### ISSUE THREAD

**Issue by AmonRay** [paulevsGitch/BCLib#39]
[latest.log](https://github.com/paulevsGitch/BCLib/files/7509040/latest.log)

just updated bclib from bclib-0.4.4.jar till 0.5.0 and got a crash on startup

**Comment by paulevsGitch** [comment]
Issue is on BetterNether side

**Comment by red2blue** [comment]
Will there be a fix for it? @paulevsGitch

**Comment by AmonRay** [comment]
its already fixed. Update BetterNether and Bclib
