### ISSUE TITLE
Overwritten RecipeManager Method Breaks Recipe Confidence

### ISSUE THREAD

**Issue by gudenau** [paulevsGitch/BCLib#42]
The [mixin for RecipeManager](https://github.com/paulevsGitch/BCLib/blob/main/src/main/java/ru/bclib/mixin/common/RecipeManagerMixin.java#L36) breaks my mod [Recipe Confidence](https://github.com/gudenau/minecraft-RecipeConfidence).

The Overwrite removes the Redirect target my mod uses to sort the recipes to determine the least fuzzy recipe to use.

Relevant issue:
https://github.com/devs-immortal/The-Aether/issues/538

**Comment by paulevsGitch** [comment]
Overwrite and Redirect conflicts with each other, and Redirect is not compatible method. I can suggest you to replace Redirect with Overwrite and increase mixin priority - if there are two Overwrites only one of them will be applied and the game will not crash. If your priority will be higher your Overwrite will be applied correctly

**Comment by davidalb97** [comment]
Is this issue fixed? I get the following warning from BCLib:
```
[main/ERROR]: 
[main/ERROR]: 
[main/ERROR]: 
[main/ERROR]: 
[main/ERROR]: bclib is incompatible with RecipeConfidence.
[main/ERROR]: 
[main/ERROR]: There is a chance that the compatibility layer is not correct, issues may arise
[main/ERROR]: when using recipes (crafting, smelting, etc.) because of the conflict.
[main/ERROR]: 
[main/ERROR]: If you are the authors of bclib and have validated the compatibility layer, feel
[main/ERROR]: free to make a mixin that changes BclibFlag.bclibCompatValidated to return true.
[main/ERROR]: 
[main/ERROR]: 
[main/ERROR]: 
[main/ERROR]: 
```
If so, shouldn't BclibFlag.bclibCompatValidated be true?

**Comment by paulevsGitch** [comment]
What is BclibFlag.bclibCompatValidated?

> Is this issue fixed?

If the original code still uses Redirect - no. Redirects are not compatible (unlike Overwrite)

**Comment by davidalb97** [comment]
> What is BclibFlag.bclibCompatValidated?
It's what it says on the error (line 11), in case the compatibility is fixed, avoiding false positive bug reporting.

**Comment by gudenau** [comment]
I added a secondary mixin that replaces your mixin in a way that allows it to be applied after yours while still overriding your functionality.

The error is going to be there until you create a small mixin to change a flag, showing that you validated the behavior of [my compatibility layer](https://github.com/gudenau/minecraft-RecipeConfidence/blob/master/src/main/java/net/gudenau/minecraft/recipeconfidence/mixin/BclibRecipeManagerMixin.java#L42).

A mixin to disable this message would look something like the following:
```Java
@Mixin(BclibFlag.class)
public abstract class BclibFlagMixin{
    /**
    * @reason This disables the compatibility warning from Recipe Confidence
    * @author gudenau
    */
    @Overwrite
    public static void bclibCompatValidated(){
        return true;
    }
}
```
