### ISSUE TITLE
BCLib 5.0

### ISSUE THREAD

**Issue by Serenitynightowl** [paulevsGitch/BCLib#49]
Couldn't figure out how to describe what is happening. We all got the mods from a shared mod folder, and every one of us get this pop-up. Unable to test other servers that have better end and better nether, as I'm not in any other server with said mods.

Syncing does nothing to aid correcting the problem, and currently have not unlocked The End, so unable to test. Images below are marked to the best of my knowledge.

![Pop-up](https://user-images.githubusercontent.com/95094882/143610762-5ca4d31f-9e4a-47c0-86de-feac3840cf45.png)
![Some mods](https://user-images.githubusercontent.com/95094882/143610763-ce5d0c11-87b4-4c28-b7e7-99e10affdb27.png)
![more mods2](https://user-images.githubusercontent.com/95094882/143610761-346ccab8-58ed-4d7e-b773-411b59b5fe48.png)
![More mods 3](https://user-images.githubusercontent.com/95094882/143610764-7610834e-253e-4e30-9731-4f33d7896317.png)
![more mods 4](https://user-images.githubusercontent.com/95094882/143610754-73ac732a-ed4e-4c42-a0f9-33dc6ed22cc4.png)
![MORE MODS 5](https://user-images.githubusercontent.com/95094882/143610759-c760d583-1336-4f5b-b1fb-b4c1abbfcfce.png)

**Comment by paulevsGitch** [comment]
BCLib 0.5.0 is outdated, can you please try the latest version?

**Comment by Serenitynightowl** [comment]
![when_crash_report_fits_one_screen](https://user-images.githubusercontent.com/95094882/143615764-fa35cdb6-be82-4d13-ba4e-d641d390a042.png)
![updated welp](https://user-images.githubusercontent.com/95094882/143615767-7cb748f2-d7d3-431b-945b-606755e70e23.png)
![welp](https://user-images.githubusercontent.com/95094882/143615769-5e2ce02e-1e41-4c5e-afbf-a91bd8ef1e8c.png)
![welp2](https://user-images.githubusercontent.com/95094882/143615770-3629d0b4-ffba-48bd-b0a5-198e2b29f4cd.png)

After removing the newest version of the mod to remove the duplicate files for fabric, just a rinse and repeat. Waiting for admin to come online to see if changing BcLib will fix it.

**Comment by paulevsGitch** [comment]
Hi, was this situation resolved or this issue is still active?

**Comment by VoronkoM** [comment]
> Hi, was this situation resolved or this issue is still active?

Yes, confirm that issue persists on BClib 1.0.3 (which is both on client and server side)

Mods claim to be not on server when they are. Clicking sync syncs configs (option greys out), but mods never get to sync (after restarts/reuplods/etc).

**Comment by quiqueck** [comment]
Mod sync is disabled by default. That Dialog is a warning to show you what is missing where. You can either activate the automatic mod sync in the BCLib configs (on server and client) or manually copy them
