### ISSUE TITLE
Ver.1.0.1 for MC1.18 Crashes Server

### ISSUE THREAD

**Issue by Joulanh** [paulevsGitch/BCLib#55]
The new Version seems to crash on servers. I tested with only fabric api and BCLib installed.

[Crashlog.txt](https://github.com/paulevsGitch/BCLib/files/7654167/Crashlog.txt)

**Comment by quiqueck** [comment]
Thanks for reporting. Will be fixed in 1.0.2

**Comment by Maja-dev** [comment]
Thanks, That commit seems to have fixed the issue

**Comment by paulevsGitch** [comment]
Fixed in 1.0.2
