### ISSUE TITLE
Crashing when on 1.18 with mods better nether and amplified nether

### ISSUE THREAD

**Issue by Spankyhp** [paulevsGitch/BCLib#56]
As titled, i have tried it with the above mods installed and its failing to start.

with the mods removed its still the same.

Thank you

**Comment by paulevsGitch** [comment]
Can you please send your logs?

**Comment by Spankyhp** [comment]
> Can you please send your logs?

I have fixed it so don't know if you would still like a log.

it was asking for BClib 0.5.5 or newer. so i was using BClib 0.5.5.

I didnt notice the 1.0.2 :(

still the loader shouldn't be asking for 0.5.5 if it doesn't work.

Thanks
