### ISSUE TITLE
BCLib on 1.18 Fabric / Players Disconnecting

### ISSUE THREAD

**Issue by red2blue** [paulevsGitch/BCLib#57]
on my latest update of my modpack, Another Quality Modpack 2 for v1.18, I've been getting numerous reports from server owners / players of my official server that they get disconnected upon joining. They are running the latest version of my modpack, meaning mods match. Some players are able to connect, and then some are not, its very weird.

https://pastebin.com/Y5bVE9W7 

https://pastebin.com/yVe335Jz

https://pastebin.com/XWwiHLP9(what is shown in server)

**Comment by quiqueck** [comment]
Those messages are just warnings, and **should** not cause a disconnect. But it could be a bug, so could disable the version tests on your server. (`config/bclib/server.json`, `auto_sync` section, set `enabled [default: true]`to `false`)

**Comment by quiqueck** [comment]
Any news on this issue? Ws it resolved for you?

**Comment by red2blue** [comment]
I have not been getting reports anymore regarding this. Looks to be good. thanks!
