### ISSUE TITLE
[Compatibility] Incompatibility with Mod Menu

### ISSUE THREAD

**Issue by LunexLunertic** [paulevsGitch/BCLib#58]
Ok, so I updated the BC lib to the latest version being 1.1.1, from 1.0.3 for Minecraft 1.18.1, and upon starting up Minecraft it immediately crashes. I don't know the exact cause of this happening but it was fine on ver 1.0.3

Here's a video to show the problem:
https://youtu.be/D6qOG0lDOgw

And here's my log showing the cause of the crash:
[latest.log](https://github.com/paulevsGitch/BCLib/files/7721691/latest.log)

**Comment by BernardoGrigiastro** [comment]
Same crash, no mods other than modmenu

https://pastebin.com/xL99N03t

**Comment by paulevsGitch** [comment]
This is incompatibility with mod menu

**Comment by quiqueck** [comment]
Can confirm, this appears to be a bug on our side
