### ISSUE TITLE
Could not find required mod: bclib requires {fabric @ [>=0.32.0]}?

### ISSUE THREAD

**Issue by rustedgoldmc** [paulevsGitch/BCLib#6]
![image](https://user-images.githubusercontent.com/83943239/123723784-bfb18e80-d850-11eb-8062-8d20e647ee74.png)
This happened. I tried all the versions of the mod and also updated Fabric. Not sure what exactly is up. Was trying to use this to run Better End.

**Comment by paulevsGitch** [comment]
You don't have Fabric API 0.32 or newer
