### ISSUE TITLE
[latest 1.18.1]changing the weights of betternether biomes doesn't work

### ISSUE THREAD

**Issue by Chuunkyz** [paulevsGitch/BCLib#63]
the weights are simply ignored

**Comment by quiqueck** [comment]
You mean `generation_chance` or the various `density`settings?

**Comment by Chuunkyz** [comment]
generation_chance, the biome itself
i want to disable the covid biome (mushroom forest) because with all the other mod features it's way too overwhelming

**Comment by quiqueck** [comment]
Could you please attach your modified the config here?

**Comment by Chuunkyz** [comment]
[bclibconfig.zip](https://github.com/paulevsGitch/BCLib/files/7799606/bclibconfig.zip)

here's my whole config

**Comment by quiqueck** [comment]
Thanks for your files. This should be fixed in the next BetterNether update (6.0.9)

**Comment by quiqueck** [comment]
6.0.9 was just release. Please re-open this issue if you still have problems wit this.
