### ISSUE TITLE
bclib 0.5.5 - 0.5.6 crashes launcher

### ISSUE THREAD

**Issue by potaterboi** [paulevsGitch/BCLib#64]
betternether requires 0.5.5 up to function on minecraft 1.17, but whenever i try to run these two versions, it crashes my launcher.

the launcher says:

ERROR
Game Crashed
An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience.

Exit Code: 0

**Comment by paulevsGitch** [comment]
Can you please provide logs?

**Comment by paulevsGitch** [comment]
So, 9 days left, no logs provided, I'm closing this
