### ISSUE TITLE
Launching dedicated server with additional args may cause crash

### ISSUE THREAD

**Issue by CmdrJane** [paulevsGitch/BCLib#67]
Specifying server arguments using "-" may result in server crash. For exmaple using C:\Users\user\jdks\openjdk-17.0.1\bin\java.exe -Xms8G -Xmx8G -jar fabric-server-launch.jar -nogui will result in server crash because of -nogui however using "nogui" in quotes will be fine and will not result in crash. 

[Crashlog](https://pastebin.com/JYN269X6)

**Comment by paulevsGitch** [comment]
"-nogui" is **not** an option of Minecraft, it is **"nogui"**, without hyphen

**Comment by paulevsGitch** [comment]
![image](https://user-images.githubusercontent.com/17707380/148722189-e0e7649f-7cfb-481f-8107-4e0e923ec5e7.png)
