### ISSUE TITLE
Enchantment menu mixin breaks Botania's pylon enchanting

### ISSUE THREAD

**Issue by Hubry** [paulevsGitch/BCLib#72]
https://github.com/paulevsGitch/BCLib/blob/8ebcf2352ac7d4a940ee1ec799972a22ef28906f/src/main/java/ru/bclib/mixin/common/EnchantmentMenuMixin.java#L58-L59

Originally reported to us as https://github.com/VazkiiMods/Botania/issues/3901

We [mix into the lambda in the same method](https://github.com/VazkiiMods/Botania/blob/d39ab5182df2cf5cd77ec8b69dafac53ab3834f6/src/main/java/vazkii/botania/mixin/MixinEnchantmentMenu.java#L34) to allow our pylons to provide a variable enchanting power, but you use an unconditional cancellable inject (which basically is an `@Overwrite` but worse) only to use a copy of the vanilla code.

**Comment by paulevsGitch** [comment]
New mixins should work fine

**Comment by paulevsGitch** [comment]
Should be fixed in 1.2.4
