### ISSUE TITLE
[Compatibility] Incompatibility with NoFog mod

### ISSUE THREAD

**Issue by rjuven2401** [paulevsGitch/BCLib#74]
I downloaded [NoFog](https://www.curseforge.com/minecraft/mc-mods/nofog) mod and then entered the end dimension with Better End mod, but the fog is still there like the following screenshots.

Minecraft version: 1.18.1 / Fabric Loader version: 0.12.12 / Fabric API version: 0.45.2
Better End version: 1.0.0 / BCLib version: 1.2.4 / [NoFog version: 1.2.0](https://www.curseforge.com/minecraft/mc-mods/nofog/files/3599894)

![2022-01-17_00 15 43](https://user-images.githubusercontent.com/96723542/149771312-ce734839-e54a-4244-910b-3d90e67572ae.png)
![2022-01-16_23 52 50](https://user-images.githubusercontent.com/96723542/149771322-633de020-9802-45bb-ae3d-ce2dc384a0b8.png)
![2022-01-17_00 15 23](https://user-images.githubusercontent.com/96723542/149771327-4ffb03de-bada-4774-b753-2b25ffe6f1ca.png)

**Comment by Vigilans** [comment]
Same, [No Fog](https://www.curseforge.com/minecraft/mc-mods/nofog) and [Custom Fog](https://www.curseforge.com/minecraft/mc-mods/custom-fog) all reported to be incompatible with BCLib.

**Comment by Vigilans** [comment]
When combining `No Fog` and `BCLib` together, the fog failed to disappear in Nether and End, but still works in Overworld. 

According to this behavior, I found code relative to it in `BCLib`:
https://github.com/paulevsGitch/BCLib/blob/d802de90f9d7ac8de523ea7c79558880c032ce05/src/main/java/ru/bclib/client/render/CustomFogRenderer.java#L36-L39

and

https://github.com/paulevsGitch/BCLib/blob/d802de90f9d7ac8de523ea7c79558880c032ce05/src/main/java/ru/bclib/client/render/CustomFogRenderer.java#L91-L93

As a workaround, I changed `isForcedDimension` to return only false, but the fog is still present. Then I checked the definition of `shouldIgnore`:

https://github.com/paulevsGitch/BCLib/blob/d802de90f9d7ac8de523ea7c79558880c032ce05/src/main/java/ru/bclib/client/render/CustomFogRenderer.java#L106-L109

Seems that `shouldIgnore` will be false when in biomes of Nether and End. As a workaround I removed this check:
```
		if (!isForcedDimension(entity.level)) { // isForcedDimension always return false
			BackgroundInfo.fogDensity = 1;
			return false;
		}
```
Now `No Fog` mod works. This couldn't be a proper fix, just post here hoping to help find a proper solution.

**Comment by idkman2021** [comment]
Does this mean its bclib that breaks distant horizons by preventing disabling vanilla fog?

**Comment by KB-Q** [comment]
Any update on this?

**Comment by paulevsGitch** [comment]
Updates are directly above your question

**Comment by idkman2021** [comment]
> Updates are directly above your question

I can't make it work with no fog or distant horizons. I disabled custom fog rendering but still renders unfaffected by other fog mods

**Comment by paulevsGitch** [comment]
Can you please show your config file?

**Comment by paulevsGitch** [comment]
Hm, can you please also attach your client logs?

**Comment by idkman2021** [comment]
> Hm, can you please also attach your client logs?

https://gist.github.com/idkman2021/fe22183f6496d86cc71eb02ed1c0c667

**Comment by paulevsGitch** [comment]
So, I tested BCLib 1.3.5 with NoFog 1.2.0 (and with ModMenu to switch BCLib config in game)

With fog (BCLib fog enabled):
![2022-03-14_19 28 17](https://user-images.githubusercontent.com/17707380/158217487-b182ab80-e4ca-4bd5-bf07-02483998eccc.png)

Without fog (BCLib fog disabled, work of NoFog mod):
![2022-03-14_19 28 30](https://user-images.githubusercontent.com/17707380/158217563-f60172cf-20c6-4259-9658-538ec29e78a9.png)

Everything works as expected. If you don't see correct fog rendering - this means conflict with other rendering mods, but not with BCLib

**Comment by idkman2021** [comment]
> So, I tested BCLib 1.3.5 with NoFog 1.2.0 (and with ModMenu to switch BCLib config in game)
> 
> With fog (BCLib fog enabled): ![2022-03-14_19 28 17](https://user-images.githubusercontent.com/17707380/158217487-b182ab80-e4ca-4bd5-bf07-02483998eccc.png)
> 
> Without fog (BCLib fog disabled, work of NoFog mod): ![2022-03-14_19 28 30](https://user-images.githubusercontent.com/17707380/158217563-f60172cf-20c6-4259-9658-538ec29e78a9.png)
> 
> Everything works as expected. If you don't see correct fog rendering - this means conflict with other rendering mods, but not with BCLib

did you test overworld?

**Comment by paulevsGitch** [comment]
> did you test overworld?

![2022-03-14_20 43 55](https://user-images.githubusercontent.com/17707380/158230449-15f19661-4d94-45e4-b523-61cc8ae4f6e1.png)

If it works in one dimension - it will work in any, Minecraft have unified code for fog rendering
