### ISSUE TITLE
[Suggestion] Drop block itself only if loottable is empty

### ISSUE THREAD

**Issue by PinkGoosik** [paulevsGitch/BCLib#78]
I think it would be nice to have this feature so people don't have to override the getDrop method to what was before

**Comment by paulevsGitch** [comment]
I think this will conflict with blocks that get changed drop with loot tables ([this suggestion](https://github.com/paulevsGitch/BetterNether/issues/486)), but we will think about it. Probably an interface can solve this

**Comment by paulevsGitch** [comment]
Implemented in 1.4.6
