### ISSUE TITLE
[bug] No liquid fog in non-overworld dimensions

### ISSUE THREAD

**Issue by DryTaste** [paulevsGitch/BCLib#81]
Liquid fog does not render correctly in other dimensions when BCLib is installed, it is worth noting however that fog seems to be functional in the overworld. 

This problem is probably related to #77 

Screenshots are provided below to illustrate the issue. 

### Expected behaviour:
![before_lava_glitch](https://user-images.githubusercontent.com/3638291/150978857-5d683d9c-4acd-4837-9072-9881d5d41815.png)
![before_water_glitch](https://user-images.githubusercontent.com/3638291/150981921-592d4eaf-af77-480e-8675-6994a3b11f8d.png)
(These screenshots are made only with the fabric API installed)

### Actual behaviour:
![after_lava_glitch](https://user-images.githubusercontent.com/3638291/150979378-2228c0fc-db3e-4ea6-b4c6-d021cc478461.png)
![after_water_glitch](https://user-images.githubusercontent.com/3638291/150981969-0e5ec9ec-b46a-457b-9413-8db35083632c.png)
(These screenshots are made with both the fabric API and BCLib installed)

### BCLib
1.2.5

### Fabric API
0.46.1

### Fabric Loader
0.12.12

### Minecraft
1.18.1

### Other mods
None

**Comment by paulevsGitch** [comment]
This is same issue as #77, but have more detailed explanation, so I will close #77 and mark this issue as a bug

**Comment by ScoobyVI** [comment]
Is there a possibility of disabling the mod's fog overwrites completely? If not, it's not a problem, but it also seems to overwrite mods that allow custom fog settings such as dense fog during rain or snow

**Comment by quiqueck** [comment]
Version 1.3.0 should fix this. Pleas re-open the issue if you still have this problem after upgrading.
