### ISSUE TITLE
Could not execute entrypoint stage 'client' due to errors, provided by 'bclib'!

### ISSUE THREAD

**Issue by TheoristAron** [paulevsGitch/BCLib#84]
[crash-2022-02-02_22.19.20-client.txt](https://github.com/paulevsGitch/BCLib/files/7992223/crash-2022-02-02_22.19.20-client.txt)
The game will crash upon startup. I attached the crash report and the title is the error I get from the launcher. I know I'm on the latest version so I don't understand where the issue lies

**Comment by paulevsGitch** [comment]
Looks like something is wrong with your Minecraft or pack - all mods in logs failed to register render layers as the class is missing

**Comment by TheoristAron** [comment]
Figured it out. Colored lights mod was the culprit for some reason
