### ISSUE TITLE
World crashes while generating if any other dimension mod presented

### ISSUE THREAD

**Issue by NordAct** [paulevsGitch/BCLib#86]
[crash-2022-02-04_21.55.13-server.txt](https://github.com/paulevsGitch/BCLib/files/8005583/crash-2022-02-04_21.55.13-server.txt)
[crash-2022-02-04_21.58.12-server.txt](https://github.com/paulevsGitch/BCLib/files/8005582/crash-2022-02-04_21.58.12-server.txt)

According to first report case crash was caused by The Corners (adds new dimensions). Then on second run I turned it off and then same error happened to VoidZ (also adds new dimension)

**Comment by JDtheHutt** [comment]
I am seeing the same with VoidZ since I updated BCLib to 1.3.0

**Comment by paulevsGitch** [comment]
Duplicate of #85
