### ISSUE TITLE
Game is not opening

### ISSUE THREAD

**Issue by TheKing8900** [paulevsGitch/BCLib#88]
Hi, I've recently been trying to open up the game, and the Minecraft software just won't open with fabric mod API and the Better dimensions (nether/end) mod packs. I assume the issue might have to do with BCLib as I've also updated to the latest in all mod software that I can find, and I have downloaded the latest uploaded mods for better dimensions. I can presume the issue is BCLib and the Better dimension mods because; as soon as they are deactivated, the software opens up fine. My latest crash log can be opened here; https://pastebin.com/xLRiuJ8d

**Comment by TheKing8900** [comment]
I know I've been having a lot of issues lately with setting these mods up and I hope this is the last one I need to be cleared up. Thanks for the help

**Comment by paulevsGitch** [comment]
You BetterEnd is outdated and don't match BClib version
