### ISSUE TITLE
New Update Causes Server Crash on World Load

### ISSUE THREAD

**Issue by AshrielV** [paulevsGitch/BCLib#90]
After updating to the most recent versions of BCLib, betterEnd & betterNether I got the crash seen below. Reverting the updates fixed the problem. Admittedly, the modpack has 300+ mods.
[crash-2022-02-04_19.33.18-server.txt](https://github.com/paulevsGitch/BCLib/files/8007010/crash-2022-02-04_19.33.18-server.txt)

**Comment by paulevsGitch** [comment]
Duplicate of #85
