### ISSUE TITLE
Server crash with BCLib 1.3.0 and Bumblezone

### ISSUE THREAD

**Issue by aisukuma** [paulevsGitch/BCLib#92]
I got this crash when I updated BCLib to 1.3.0
`java.lang.ClassCastException: class com.telepathicgrunt.the_bumblezone.world.dimension.BzChunkGenerator cannot be cast to class ru.bclib.interfaces.NoiseGeneratorSettingsProvider (com.telepathicgrunt.the_bumblezone.world.dimension.BzChunkGenerator and ru.bclib.interfaces.NoiseGeneratorSettingsProvider are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @68837a77)`

Here is the crash report:
[crash-2022-02-05_00.21.05-server.txt](https://github.com/paulevsGitch/BCLib/files/8007436/crash-2022-02-05_00.21.05-server.txt)

Here is the latest log:
[latest.log](https://github.com/paulevsGitch/BCLib/files/8007438/latest.log)

If it's on their end, I'll link it to their Github page.

**Comment by aisukuma** [comment]
Maybe a duplicate of #85? If so, you can close this.

**Comment by Redd56** [comment]
Let me check

**Comment by Redd56** [comment]
Looks like it prolly is
