### ISSUE TITLE
Crash when joining world

### ISSUE THREAD

**Issue by SirKrunk** [paulevsGitch/BCLib#97]
[crash-2022-02-06_09.29.54-server.txt](https://github.com/paulevsGitch/BCLib/files/8009315/crash-2022-02-06_09.29.54-server.txt)

**Comment by FirstMegaGame4** [comment]
BCLib 1.3.0 is not the newest version.
Update to BCLib 1.3.1.

**Comment by paulevsGitch** [comment]
It was fixed in 1.3.1

**Comment by SirKrunk** [comment]
ok
