### ISSUE TITLE
Constantly says "Mismatching Data"

### ISSUE THREAD

**Issue by the-unheard** [paulevsGitch/BCLib#98]
Whenever I join our server, it keeps saying I have mismatching data, and that a lot of mods don't exist on the server even though they do. Whether I synchronize or not, the next time I join our server, the warning pops up again.

Mod list here in this log:
https://mclo.gs/z6QVubG

**Comment by paulevsGitch** [comment]
Can you please send logs with latest mods version and when you actually get this message? From both server and client
